package client.socket;
/*
 * Interface used for communication
 * between socket layer and ViewModel.
 */
public interface SocketListener {

    void onBroadcastReceived(String message);

    void onIntervalChanged(int newInterval);

    void onConnectionLost();

    /*
     * Called whenever a new temperature
     * is generated by the sensor.
     */
    void onTemperatureGenerated(
            double temperature,
            double average,
            double highest,
            int measurements);
}
